federation_version: 2
subgraphs:
  azimuth:
    routing_url: http://localhost:3001/graphql
    schema:
      file: ./packages/azimuth-watcher/src/subgraph-schema.gql
  censures:
    routing_url: http://localhost:3002/graphql
    schema:
      file: ./packages/censures-watcher/src/schema.gql
  claims:
    routing_url: http://localhost:3003/graphql
    schema:
      file: ./packages/claims-watcher/src/schema.gql
  conditional_star_release:
    routing_url: http://localhost:3004/graphql
    schema:
      file: ./packages/conditional-star-release-watcher/src/schema.gql
  delegated_sending:
    routing_url: http://localhost:3005/graphql
    schema:
      file: ./packages/delegated-sending-watcher/src/schema.gql
  ecliptic:
    routing_url: http://localhost:3006/graphql
    schema:
      file: ./packages/ecliptic-watcher/src/schema.gql
  linear_star_release:
    routing_url: http://localhost:3007/graphql
    schema:
      file: ./packages/linear-star-release-watcher/src/schema.gql
  polls:
    routing_url: http://localhost:3008/graphql
    schema:
      file: ./packages/polls-watcher/src/schema.gql
